Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provider "virtualbox" do |v|
    v.name = "fluid-zebra"
  end
  config.vm.network "public_network"
  config.vm.synced_folder "../../../builder", "/builder/builder"
  config.vm.provider "virtualbox" do |v|
    v.name = "fluid-zebra"
  end
  config.vm.network "public_network"
  config.vm.synced_folder "../../../builder", "/builder/builder"
  config.vm.provider "virtualbox" do |v|
    v.name = "fluid-zebra"
  end
  config.vm.network "public_network"
  config.vm.synced_folder "../../../builder", "/builder/builder"
end
